### ISSUE TITLE
cluster上面跑的报错

### ISSUE THREAD

**Issue by ychen664** [kkyyhh96/Large_Scale_GWR#1]
`yuhua@node1:~$ python GWR_v1.py -k 5 -f ~/house_shp_sample.shp -n 3 -t 2 -m KNN
/mnt/data/conda3/lib/python3.8/site-packages/pysal/model/spvcm/abstracts.py:10: UserWarning: The `dill` module is required to use the sqlite backend fully.
  from .sqlite import head_to_sql, start_sql
KNN
/mnt/data/conda3/lib/python3.8/site-packages/libpysal/weights/weights.py:172: UserWarning: The weights matrix is not fully connected: 
 There are 2 disconnected components.
  warnings.warn(message)
Traceback (most recent call last):
  File "GWR_v1.py", line 81, in <module>
    main()
  File "GWR_v1.py", line 75, in main
    Y_pred = gwr_model.estimate(x_name = ['Baths','Beds'], chunk=10)
  File "GWR_v1.py", line 65, in estimate
    return da.concatenate(Y_pred).ravel().compute()
  File "/mnt/data/conda3/lib/python3.8/site-packages/dask/base.py", line 167, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/mnt/data/conda3/lib/python3.8/site-packages/dask/base.py", line 452, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/mnt/data/conda3/lib/python3.8/site-packages/distributed/client.py", line 2725, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/mnt/data/conda3/lib/python3.8/site-packages/distributed/client.py", line 1986, in gather
    return self.sync(
  File "/mnt/data/conda3/lib/python3.8/site-packages/distributed/client.py", line 832, in sync
    return sync(
  File "/mnt/data/conda3/lib/python3.8/site-packages/distributed/utils.py", line 340, in sync
    raise exc.with_traceback(tb)
  File "/mnt/data/conda3/lib/python3.8/site-packages/distributed/utils.py", line 324, in f
    result[0] = yield future
  File "/mnt/data/conda3/lib/python3.8/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/mnt/data/conda3/lib/python3.8/site-packages/distributed/client.py", line 1851, in _gather
    raise exception.with_traceback(traceback)
  File "/mnt/data/conda3/lib/python3.8/site-packages/scipy/linalg/basic.py", line 355, in solve_triangular
    raise LinAlgError("singular matrix: resolution failed at diagonal %d" %
numpy.linalg.LinAlgError: singular matrix: resolution failed at diagonal 1`

**Comment by PhanTask** [comment]
Please Change KNN to Kernel to temporally avoid singular matrix.

**Comment by ychen664** [comment]
Resolved
